"""Generate Markdown taste report."""

from __future__ import annotations

from taste.data.models import TasteProfile


def render_markdown(profile: TasteProfile) -> str:
    lines: list[str] = []
    author = profile.author

    # Title
    lines.append(f"# Research Taste: {author.name}\n")
    if profile.one_liner:
        lines.append(f"> {profile.one_liner}\n")

    # Overview table
    high_count = sum(1 for pa in profile.phase_analyses for p in pa.phase.papers if p.contribution_level == "high")
    fill_count = profile.papers_analyzed - high_count

    lines.append("## Overview\n")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Papers Analyzed | {profile.papers_analyzed} (high-contribution {high_count}, fill {fill_count}) |")
    lines.append(f"| Total Citations | {author.citation_count:,} |" if author.citation_count else "")
    lines.append(f"| h-index | {author.h_index} |" if author.h_index else "")

    # Career span
    years = []
    for pa in profile.phase_analyses:
        for p in pa.phase.papers:
            if p.year:
                years.append(p.year)
    if years:
        lines.append(f"| Active Years | {min(years)}-{max(years)} |")

    # Institution trajectory
    all_aff = []
    for phase in profile.career.phases:
        for a in phase.affiliations:
            if a and a not in all_aff:
                all_aff.append(a)
    if all_aff:
        lines.append(f"| Institutions | {' → '.join(all_aff)} |")
    lines.append("")

    # Career timeline
    lines.append("## Career Timeline\n")
    for pa in profile.phase_analyses:
        phase = pa.phase
        aff_str = f" @ {', '.join(phase.affiliations)}" if phase.affiliations else ""
        lines.append(f"### {phase.name} ({phase.years}){aff_str}\n")

        # Phase observations as prose
        for key, obs in pa.observations.items():
            lines.append(f"**{key.replace('_', ' ').title()}**: {obs}\n")

        # Representative papers
        if pa.representative_papers:
            lines.append("**Key papers**:")
            for p in pa.representative_papers:
                pos = f", {p.author_position}" if p.author_position != "unknown" else ""
                lines.append(f"- *{p.title}* ({p.year or '?'}{pos}, {p.citation_count:,} citations)")
            lines.append("")

    # Taste dimensions
    lines.append("## Taste Profile\n")
    for dim in profile.dimensions:
        lines.append(f"### {dim.name}\n")
        lines.append(f"{dim.summary}\n")
        if dim.evidence:
            lines.append("Evidence: " + ", ".join(f"*{e}*" for e in dim.evidence) + "\n")

    # Tags
    if profile.tags:
        lines.append("## Taste Tags\n")
        lines.append(" ".join(f"`{t}`" for t in profile.tags) + "\n")

    # Key papers
    if profile.key_papers:
        lines.append("## Key Representative Papers\n")
        for i, p in enumerate(profile.key_papers, 1):
            pos = f", {p.author_position}" if p.author_position != "unknown" else ""
            lines.append(f"{i}. **{p.title}** ({p.year or '?'}{pos}, {p.citation_count:,} citations)")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("*Generated by [taste](https://github.com/rain-research/taste) | Paper is cheap, show me the taste.*")

    return "\n".join(lines)
